name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
      with:
        python-version: 3.6
    - uses: actions/cache@v1
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    # Don't install editable projects in the current working directory.
    # https://pip.pypa.io/en/latest/reference/pip_install/#install-src
    - run: pip install --src $GITHUB_WORKSPACE/../src -r requirements.txt
    # Google Chrome and ChromeDriver are already included.
    # https://help.github.com/en/actions/reference/software-installed-on-github-hosted-runners
    - name: Make and test
      run: |
        if [ $GITHUB_REPOSITORY = 'open-contracting/standard_profile_template' ]; then python schema/build-profile.py; make extract; fi
        make
        pytest
    - uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.PRIVATE_KEY }}
    - if: success()
      env:
        LANGS: en
        PATH_PREFIX: profiles/gpa/
        SEARCH_SECRET: ${{ secrets.SEARCH_SECRET }}
      run: curl -Ss https://raw.githubusercontent.com/open-contracting/deploy/master/deploy-docs.sh | bash -
